# Generated by Django 4.1.3 on 2022-11-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_created_at_post_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
